_2d6‍.x([["errorHandler",()=>errorHandler]]);const errorHandler = (fn) =>
    (req, res, next) => {
        Promise.resolve(fn(req, res, next))
            .catch(next);
    }